### ISSUE TITLE
Declare the dependencies

### ISSUE THREAD

**Issue by maximlt** [Doodleverse/doodler_engine#1]
Now that we have our hands untied after the `pydensecrf` package has been updated on conda-forge, I would suggest if possible:

1. declaring the dependencies on which `doodler_engine` rely, by listing them in the setup.py file. I think it'd be possible to declare them instead in the setup.cfg file or in the pyproject.toml file, Python Packaging is evolving and being standardized, but I think you should be fine with listing them in the setup.py. If you are aware of some pins (for example this sort of pin numpy>1.5, <=.1.7), 
2. When 1. is done, make a release on PyPi
3.  When 2. is done, create a conda-forge recipe, this is usually pretty straightforward and I can help with that
4. When 3. is done, both dash-doodler and holodoodler can update their environments.yml to declare their dependency of `doodler_engine`

Given that dash-doodler and holodoodler are more of the application type of software vs. the library type, it'd be worth using `anaconda-project` to record:

* how to launch the application, e.g. with holodoodler that would be recording `panel serve app.py --show`
* an exact list of dependencies that are known to be working together. We call that creating a lock file and this is achieved with `anaconda-project lock`. When you tell your users to create their environment with `anaconda-project prepare`, if the lock file exists they will get the exact versions declared in the lock file, be it tomorrow or in a few years, which helps with making your work reproducible, and is good practice when you're managing an application.

**Comment by ddbuscombe** [comment]
Sounds like a plan! Thanks for the detailed advice. I'll try to find time later this week

**Comment by ddbuscombe** [comment]
I may need help with the conda-forge recipe because that's not something I have ever done

**Comment by maximlt** [comment]
Hi @dbuscombe-usgs, just checking if you still intend to make the updates I suggested. Still happy to help with the conda-forge recipe!

**Comment by ddbuscombe** [comment]
Hi @maximlt yes this is still the plan ... still trying to make some time to do it, so I'd be happy if you wanted to take this on! Thanks

**Comment by maximlt** [comment]
Ok I'll give it a try in the next few days!

**Comment by ddbuscombe** [comment]
thank you!!

**Comment by maximlt** [comment]
Just to report that I've started a branch to package this more nicely. I aim to set up some simple CI for you to easily release a new version and for running an (eventual) test suite.

**Comment by ddbuscombe** [comment]
Thank you! 😊

**Comment by ddbuscombe** [comment]
Closing this as per discussion in https://github.com/Doodleverse/doodler_engine/pull/3
